# Generated by Django 3.2.4 on 2021-10-12 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('Agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('visibility', models.CharField(blank=True, max_length=100)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('Keyword_ids', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=100)),
                ('definition', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Info_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('Topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handlerapp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='topicKeyword',
            fields=[
                ('Keyword_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Keyword', models.ManyToManyField(to='handlerapp.Keyword')),
                ('Topic', models.ManyToManyField(to='handlerapp.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('pre_condition', models.CharField(blank=True, max_length=255)),
                ('effect', models.CharField(blank=True, max_length=255)),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handlerapp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Movie_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.CharField(blank=True, max_length=10, null=True)),
                ('genres', models.ManyToManyField(to='handlerapp.Movie_Info_genre')),
            ],
        ),
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False)),
                ('startdate', models.CharField(blank=True, max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTopic',
            fields=[
                ('name_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent', models.ManyToManyField(to='handlerapp.Agent')),
                ('topic', models.ManyToManyField(to='handlerapp.Topic')),
            ],
        ),
    ]
