# Generated by Django 3.2.4 on 2021-10-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handlerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topickeyword',
            old_name='Keyword',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='topickeyword',
            old_name='Topic',
            new_name='topics',
        ),
    ]
